I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4, in script
    show screen diss
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen diss is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4, in script
    show screen diss
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 1974, in execute
    self.call("execute")
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 1327, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen diss is not known.


Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
Prototype_Capstone 1.0
Fri Nov  1 09:12:32 2024
